name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
            echo "hello world"
            echo "printing second line"
        
      - name: Print good bye
        run: echo "good bye"
